experiment:
  name: unet_v4_1m_mae_sce

data:
  root: "E:/PycharmProjects/SnowPrediction/dataset_v4_fisico"
  csv_file: "dataset_v4_fisico.csv"
  images_dir: "images"
  masks_dir: "masks"
  source: "lidar"
  split_type: "temporal"
  use_sce: true          # <-- Canal 6 activado (imagen satelite SCE)

model:
  architecture: "unet"
  in_channels: 6         # <-- 5 topograficos + 1 SCE
  out_channels: 1

training:
  batch_size: 16
  learning_rate: 0.0001
  epochs: 150
  loss: "mae"
  num_workers: 0
  device: "auto"

output:
  models_dir: "E:/PycharmProjects/SnowPrediction/Articulo 1/Models"
  results_dir: "E:/PycharmProjects/SnowPrediction/results/unet_v4_1m_mae_sce"
  model_name: "unet_v4_1m_mae_sce"
